### ISSUE TITLE
exit trap suppresses non-zero exit codes

### ISSUE THREAD

**Issue by cspotcode** [veqryn/kube-cloudwatch-autoscaler#7]
As far as I can tell, every `exit 1` is being trapped and converted to `exit 0`.

https://github.com/veqryn/kube-cloudwatch-autoscaler/blob/b9af65f87ad217d915710b38e2989f670d5056a3/entrypoint.sh#L84
https://github.com/veqryn/kube-cloudwatch-autoscaler/blob/b9af65f87ad217d915710b38e2989f670d5056a3/entrypoint.sh#L52-L53

Is this intentional?

**Comment by martin-walsh** [comment]
Fixed by https://github.com/veqryn/kube-cloudwatch-autoscaler/pull/10
