### ISSUE TITLE
LOG_LEVEL environment variable.

### ISSUE THREAD

**Issue by martin-walsh** [veqryn/kube-cloudwatch-autoscaler#9]
Hi,

Just reaching out to know if you would accept a contribution to add log levels to the autoscaler. We use this great app and the only downside is it creates a lot of logging.

Thoughts would be to add an `log_info` & `log_error` function to wrap the printf calls. and potentially add `INFO: ` & `ERROR: ` prefixes.

Thanks,

Martin

**Comment by veqryn** [comment]
Sure

**Comment by martin-walsh** [comment]
Cool. I'll whip something up for review
